Split transposed convolution to conv transpose2d
webmachinelearning/webnn-polyfill pull request #145
Opened 2021-12-08 08:06 UTC by wangli69087

@BruceDai Please help me review this PR. Thanks.

2021-12-08 08:13 UTC, BruceDai commented
@wangli69087, please clean your commits, only submit the commit for "Split transposed convolution to conv transpose2d", thanks.

2021-12-08 10:34 UTC, BruceDai requested changes
@wangli69087 Please update filter layout for conv2d and convTranspose2d ops, and add some tests to check convTranspose2d with `iohw `| `hwoi` filter layouts.

2021-12-08 10:34 UTC, BruceDai commented on src/nn/graph_builder.ts
> +      MLOperand {
Please update
```ts
  convTranspose2d(input: MLOperand, filter: MLOperand, 
    options: MLConvTranspose2dOptions = {}):
      MLOperand {
```
to
```ts
  convTranspose2d(
      input: MLOperand, filter: MLOperand,
      options: MLConvTranspose2dOptions = {}): MLOperand {
```

2021-12-08 10:34 UTC, BruceDai commented on src/nn/graph_builder.ts
> +  filterLayout?: MLFilterOperandLayout;
`MLFilterOperandLayout` is outdated, please change `MLFilterOperandLayout` to `MLConv2dFilterOperandLayout`, and also rename above enum `MLFilterOperandLayout` to `MLConv2dFilterOperandLayout`.

2021-12-08 10:34 UTC, BruceDai commented on src/nn/graph_builder.ts
>    filterLayout?: MLFilterOperandLayout;
Please change `MLFilterOperandLayout` to `MLConvTranspose2dFilterOperandLayout`.

2021-12-08 10:34 UTC, BruceDai commented on src/nn/ops/conv2d.ts
>    private filterLayout_?: MLFilterOperandLayout;
ditto

2021-12-08 10:34 UTC, BruceDai commented on src/nn/ops/conv2d.ts
>        filterLayout: MLFilterOperandLayout = MLFilterOperandLayout.oihw,
ditto

2021-12-08 10:34 UTC, BruceDai commented on src/nn/ops/conv2d.ts
> +      filter = tf.transpose(filter, [2, 3, 1, 0]);
ditto

2021-12-08 10:34 UTC, BruceDai commented on src/nn/ops/convtranspose2d.ts
> +import {MLAutoPad, MLConvTranspose2dOptions, MLFilterOperandLayout, MLInputOperandLayout} from '../graph_builder';
ditto

2021-12-08 10:34 UTC, BruceDai commented on src/nn/ops/convtranspose2d.ts
> +  private filterLayout_?: MLFilterOperandLayout;
ditto

2021-12-08 10:34 UTC, BruceDai commented on src/nn/ops/convtranspose2d.ts
> +      filterLayout: MLFilterOperandLayout = MLFilterOperandLayout.oihw,
ditto

2021-12-08 10:34 UTC, BruceDai commented on src/nn/ops/convtranspose2d.ts
> +        filterLayout in MLFilterOperandLayout,
ditto

2021-12-08 10:34 UTC, BruceDai commented on src/nn/ops/convtranspose2d.ts
> +      if (this.filterLayout_ === MLFilterOperandLayout.oihw) {
ditto
Please process these tree convTranspose2d filter layout: "iohw" | "hwoi" | "ohwi".

2021-12-08 10:34 UTC, BruceDai commented on test/ops/convtranspose2d.js
> +  it('conv2d transpose nchw ihwo', function() {
There's none `ihwo` ConvTranspose2d filter layout, please add some tests with `iohw` | `hwoi` filter layouts.

2021-12-08 10:34 UTC, BruceDai commented on test/ops/convtranspose2d.js
> +  it('conv2d transpose nhwc hwio', function() {
ditto

2021-12-13 10:15 UTC, BruceDai commented
LGTM, thanks @wangli69087

2021-12-13 10:15 UTC, BruceDai approved these changes

2021-12-16 01:52 UTC, BruceDai requested changes
@wangli69087 There are some links need to update, and please remove `outputPadding` option from `conv2d` op, move some tests to `conv_transpose2d.js` file.

2021-12-16 01:52 UTC, BruceDai commented on src/nn/graph_builder.ts
>   * [spec](https://webmachinelearning.github.io/webnn/#enumdef-mlfilteroperandlayout)
@wangli69087 Please update this link, thanks.

2021-12-16 01:52 UTC, BruceDai commented on src/nn/graph_builder.ts
> + * [spec](https://webmachinelearning.github.io/webnn/#enumdef-mlfilteroperandlayout)
ditto

2021-12-16 01:52 UTC, BruceDai commented on src/nn/graph_builder.ts
> +  outputPadding?: [number, number];
There isn't `outputPadding` option for [`MLConv2dOptions`](https://webmachinelearning.github.io/webnn/#dictdef-mlconv2doptions), please remove it.

2021-12-16 01:52 UTC, BruceDai commented on src/nn/ops/conv2d.ts
> +      outputPadding: [number, number] = [0, 0], bias: MLOperand = undefined,
ditto

2021-12-16 01:52 UTC, BruceDai commented on src/nn/ops/conv2d.ts
>    private outputPadding_?: [number, number];
Please remove this variable.

2021-12-16 01:52 UTC, BruceDai commented on src/nn/ops/conv2d.ts
> +        options.outputPadding, options.bias, options.activation);
ditto

2021-12-16 01:52 UTC, BruceDai commented on src/nn/ops/conv2d.ts
> +    this.outputPadding_ = outputPadding;
ditto

2021-12-16 01:52 UTC, BruceDai commented on src/nn/ops/conv2d.ts
>          input, filter, this.padding_, this.strides_, this.outputPadding_,
Replace  `this.outputPadding` with `[0,0]`

2021-12-16 01:52 UTC, BruceDai commented on test/ops/conv2d.js
>    it('conv2d transpose false', function() {
Move these tests to conv_transpose2d.js test file.

2021-12-22 07:48 UTC, BruceDai reviewed
@wangli69087 Pleas update error message for `groups` and `dilations` options checking.

2021-12-22 07:48 UTC, BruceDai commented on src/nn/ops/conv_transpose2d.ts
> +      'The tf.convtranspose2d does not support dilations parameter.');
Please update `tf.convtranspose2d` to `tf.conv2dTranspose`.

2021-12-22 07:48 UTC, BruceDai commented on src/nn/ops/conv_transpose2d.ts
> +      'The tf.convtranspose2d does not support groups parameter.');
ditto

2021-12-22 08:59 UTC, BruceDai approved these changes

2021-12-22 09:00 UTC, BruceDai commented
LGTM, thanks @wangli69087
 
@huningxin Would you please take a look, thanks.

2021-12-22 13:38 UTC, huningxin approved these changes
LGTM, thanks!

2021-12-22 13:38 UTC, merged